# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 11

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -10 до 0.

Сделайте это двумя способами:

**Вывод**

```
array([-10, -9, -8, -7, -6, -5, -4, -3, -2, -1,  0])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 9×9 со всеми значениями, равными `False`.

*Подсказка:* создайте массив из нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 8×8, заполненный случайными целыми числами в интервале от 15 до 85.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении пятой строки второго столбца
3.   Элемент на пересечении первой строки седьмого столбца
4.   Элемент на пересечении восьмой строки четвёртого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[52 68 31 77 43 59 82 36]
 [71 48 65 29 54 67 38 75]
 [63 37 73 61 52 84 46 69]
 [45 78 56 33 72 41 58 67]
 [84 47 62 55 39 76 51 43]
 [36 69 44 71 58 35 82 49]
 [57 53 68 45 81 39 74 56]
 [74 56 43 69 47 64 58 72]]
47
82
69
52
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 9.

In [ ]:
test_array = np.array([27, -18, 19, 9, -14, 36, 11, -9, 45, 10])

**Вывод**

```
array([ 27, -18,   9,  36,  -9,  45])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 2, и меньше или равны 9.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([1, 6, 17, 3, 9, -3, 14, 7, 10, 2])

**Вывод**

```
array([6, 3, 9, 7])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 9, на `90`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([27, -18, 19, 9, -14, 36, 11, -9, 45, 10])
```

**Вывод:**

```
array([90, 90, 19, 90, -14, 90, 11, 90, 90, 10])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[35 62 48 71 54]
 [59 41 77 52 68]
 [56 45 64 50 73]]
Количество элементов массива, равных значению середины интервала от a1 до a2: 2
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 12·x² + 9·sin(x) + 8·exp(-x/18)

Запрограммируйте функцию с использованием возможностей numpy

`y = 12*x**2 + 9*sin(x) + 8*exp(-x/18)`

Создайте массив 6×2 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]]
```

**Вывод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]]
---------------
[[51.74704812 15.38247143]
 [110.06019121  8.        ]
 [194.34144069 51.74704812]
 [15.38247143 110.06019121]
 [ 8.        194.34144069]
 [51.74704812  8.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[8 3 5]
 [2, 6, 4]]

[[3 1]
 [2, 5]
 [4, 2]]

[[2 1 3]
 [1, 3, 2]]
```



**Вывод**

```
[[8 2]
 [3 6]
 [5 4]]

[[50 33]
 [34 44]]

[[16  3 15]
 [ 2 18  8]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
