# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 32

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -30 до -20.

Сделайте это двумя способами:

**Вывод**

```
array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6, где первые четыре столбца содержат значения `False`, а остальные столбцы содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 9×9, заполненный случайными целыми числами в интервале от 135 до 185.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении седьмой строки девятого столбца
3.   Элемент на пересечении пятой строки пятого столбца
4.   Элемент на пересечении девятой строки седьмого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[182 160 180 167 174 181 178 184 185]
 [173 185 178 161 180 185 185 185 185]
 [185 167 185 175 182 185 185 185 185]
 [180 165 185 172 183 183 185 185 185]
 [178 162 185 172 185 185 185 185 185]
 [178 171 185 177 185 185 185 185 185]
 [178 171 185 177 185 185 185 185 185]
 [178 171 185 177 185 185 185 185 185]
 [178 171 185 177 185 185 185 185 185]]
185
185
185
182
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 30.

In [ ]:
test_array = np.array([90, -60, 61, 30, -35, 120, 33, -30, 150, 32])

**Вывод**

```
array([ 90, -60,  30, 120, -30, 150])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 15, и строго меньше 22.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([14, 27, 38, 21, 22, -24, 35, 21, 32, 20])

**Вывод**

```
array([21, 21, 20])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 30, на `300`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([90, -60, 61, 30, -35, 120, 33, -30, 150, 32])
```

**Вывод:**

```
array([300, 300,  61, 300, -35, 300,  33, 300, 300,  32])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[99 125 111 134 117]
 [122 104 139 115 131]
 [119 108 127 113 136]]
Количество элементов массива, не равных значению середины интервала от a1 до a2: 15
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 33·x² + 30·cos(x) + 29·exp(-x/120)

Запрограммируйте функцию с использованием возможностей numpy

`y = 33*x**2 + 30*cos(x) + 29*exp(-x/120)`

Создайте массив 5×6 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4 1]
 [2 3 0 4 2 3]
 [1 0 4 2 3 1]
 [3 4 0 1 2 0]
 [4 3 2 0 1 3]]
```

**Вывод:**

```
[[2 1 3 0 4 1]
 [2 3 0 4 2 3]
 [1 0 4 2 3 1]
 [3 4 0 1 2 0]
 [4 3 2 0 1 3]]
---------------
[[198.74704812 99.38247143 299.06019121 29. 530.34144069 99.38247143]
 [198.74704812 299.06019121 29. 530.34144069 198.74704812 299.06019121]
 [99.38247143 29. 530.34144069 198.74704812 299.06019121 99.38247143]
 [299.06019121 530.34144069 29. 99.38247143 198.74704812 29.]
 [530.34144069 299.06019121 198.74704812 29. 99.38247143 299.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `c`.

**Ввод**

```
[[29 24 26]
 [23, 27, 25]]

[[20 18 20]
 [18, 19, 18]]

[[17 18 19]
 [18, 17, 18]]
```



**Вывод**

```
[[29 23]
 [24 27]
 [26 25]]

[[1.45 1.33333333 1.3]
 [1.27777778 1.42105263 1.38888889]]

[[46 42 45]
 [41 44 43]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 8, 5, 6, 9, 2, 7, 4, 1, 0]
b = [2, 7, 6, 9, 5, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
