# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 10

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -9 до 1.

Сделайте это двумя способами:

**Вывод**

```
array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 8×8 со всеми значениями, равными `True`.

*Подсказка:* создайте массив из единиц и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 7×7, заполненный случайными целыми числами в интервале от 10 до 80.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении четвёртой строки третьего столбца
3.   Элемент на пересечении второй строки шестого столбца
4.   Элемент на пересечении седьмой строки пятого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[45 62 31 58 47 69 53]
 [38 72 41 56 34 67 29]
 [84 48 63 52 44 76 51]
 [65 27 59 42 68 35 73]
 [46 81 37 75 54 62 49]
 [57 33 68 45 82 39 71]
 [74 56 43 69 58 47 64]]
59
67
58
45
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 8.

In [ ]:
test_array = np.array([24, -16, 17, 8, -12, 32, 10, -8, 40, 9])

**Вывод**

```
array([ 24, -16,   8,  32,  -8,  40])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 5, и строго меньше 12.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([4, 9, 16, 6, 12, -2, 13, 8, 11, 5])

**Вывод**

```
array([9, 6, 8, 11, 5])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 8, на `80`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([24, -16, 17, 8, -12, 32, 10, -8, 40, 9])
```

**Вывод:**

```
array([80, 80, 17, 80, -12, 80, 10, 80, 80,  9])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго превышающих значение середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[32 65 48 72 55]
 [61 42 78 53 69]
 [57 46 64 51 74]]
Количество элементов массива, строго превышающих значение середины интервала от a1 до a2: 9
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 11·x² + 8·cos(x) + 7·exp(-x/15)

Запрограммируйте функцию с использованием возможностей numpy

`y = 11*x**2 + 8*cos(x) + 7*exp(-x/15)`

Создайте массив 5×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[1 3 2]
 [0 4 1]
 [3 2 0]
 [4 1 3]
 [2 0 4]]
```

**Вывод:**

```
[[1 3 2]
 [0 4 1]
 [3 2 0]
 [4 1 3]
 [2 0 4]]
---------------
[[16.38247143 101.06019121 45.87352406]
 [ 7.         178.34144069 16.38247143]
 [101.06019121 45.87352406  7.        ]
 [178.34144069 16.38247143 101.06019121]
 [45.87352406  7.        178.34144069]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[7 2 4]
 [3, 5, 1]]

[[2 5]
 [4, 2]
 [3, 1]]

[[1 3 2]
 [2, 1, 3]]
```



**Вывод**

```
[[7 3]
 [2 5]
 [4 1]]

[[34 43]
 [29 26]]

[[ 7  6  8]
 [ 6  5  3]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 9, 6, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
