# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 14

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -12 до -2.

Сделайте это двумя способами:

**Вывод**

```
array([-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 7×7, где первые четыре строки содержат значения `False`, а остальные строки содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 5×5, заполненный случайными целыми числами в интервале от 40 до 90.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении второй строки четвёртого столбца
3.   Элемент на пересечении пятой строки первого столбца
4.   Элемент на пересечении третьей строки пятого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[67 52 84 71 45]
 [58 93 46 79 62]
 [81 54 69 42 88]
 [73 48 56 85 51]
 [64 77 39 68 82]]
79
64
88
67
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 12.

In [ ]:
test_array = np.array([36, -24, 25, 12, -17, 48, 15, -12, 60, 14])

**Вывод**

```
array([ 36, -24,  12,  48, -12,  60])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 6, и строго меньше 13.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([5, 9, 20, 6, 13, -6, 17, 10, 14, 7])

**Вывод**

```
array([9, 6, 10, 7])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 12, на `120`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([36, -24, 25, 12, -17, 48, 15, -12, 60, 14])
```

**Вывод:**

```
array([120, 120,  25, 120, -17, 120,  15, 120, 120,  14])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[45 71 57 80 63]
 [68 50 85 61 77]
 [65 54 73 59 82]]
Количество элементов массива, не равных значению середины интервала от a1 до a2: 15
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 15·x² + 12·cos(x) + 11·exp(-x/30)

Запрограммируйте функцию с использованием возможностей numpy

`y = 15*x**2 + 12*cos(x) + 11*exp(-x/30)`

Создайте массив 9×2 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]
 [4 2]
 [1 0]]
```

**Вывод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]
 [4 2]
 [1 0]]
---------------
[[72.74704812 27.38247143]
 [137.06019121 11.        ]
 [242.34144069 72.74704812]
 [27.38247143 137.06019121]
 [11.        242.34144069]
 [72.74704812 11.        ]
 [137.06019121 27.38247143]
 [242.34144069 72.74704812]
 [27.38247143 11.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `c`.

**Ввод**

```
[[11 6 8]
 [5, 9, 7]]

[[3 2 4]
 [1, 3, 2]]

[[2 1 3]
 [1, 2, 1]]
```



**Вывод**

```
[[11 5]
 [6 9]
 [8 7]]

[[14  8 12]
 [ 6 12  9]]

[[ 9  5  5]
 [ 4  7  6]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 9, 6, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
