# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 33

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -31 до -21.

Сделайте это двумя способами:

**Вывод**

```
array([-31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6, где первые пять строк содержат значения `True`, а последняя строка содержит значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 10×10, заполненный случайными целыми числами в интервале от 140 до 190.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении восьмой строки десятого столбца
3.   Элемент на пересечении шестой строки шестого столбца
4.   Элемент на пересечении десятой строки восьмого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[189 167 187 174 181 188 185 190 190 190]
 [180 190 185 168 187 190 190 190 190 190]
 [190 174 190 182 189 190 190 190 190 190]
 [187 172 190 179 190 190 190 190 190 190]
 [185 169 190 179 190 190 190 190 190 190]
 [185 178 190 184 190 190 190 190 190 190]
 [185 178 190 184 190 190 190 190 190 190]
 [185 178 190 184 190 190 190 190 190 190]
 [185 178 190 184 190 190 190 190 190 190]
 [185 178 190 184 190 190 190 190 190 190]]
190
190
190
189
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 31.

In [ ]:
test_array = np.array([93, -62, 63, 31, -36, 124, 34, -31, 155, 33])

**Вывод**

```
array([ 93, -62,  31, 124, -31, 155])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 14, и меньше или равны 21.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([13, 28, 39, 21, 21, -25, 36, 21, 33, 20])

**Вывод**

```
array([21, 21, 21, 20])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 31, на `310`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([93, -62, 63, 31, -36, 124, 34, -31, 155, 33])
```

**Вывод:**

```
array([310, 310,  63, 310, -36, 310,  34, 310, 310,  33])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, больших или равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[102 128 114 137 120]
 [125 107 142 118 134]
 [122 111 130 116 139]]
Количество элементов массива, больших или равных значению середины интервала от a1 до a2: 10
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 34·x² + 31·sin(x) + 30·exp(-x/125)

Запрограммируйте функцию с использованием возможностей numpy

`y = 34*x**2 + 31*sin(x) + 30*exp(-x/125)`

Создайте массив 6×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 4 0 1 2]
 [4 3 2 0 1]
 [2 0 4 1 3]]
```

**Вывод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 4 0 1 2]
 [4 3 2 0 1]
 [2 0 4 1 3]]
---------------
[[205.74704812 103.38247143 308.06019121 30. 546.34144069]
 [103.38247143 205.74704812 30. 308.06019121 546.34144069]
 [30. 308.06019121 205.74704812 546.34144069 103.38247143]
 [308.06019121 546.34144069 30. 103.38247143 205.74704812]
 [546.34144069 308.06019121 205.74704812 30. 103.38247143]
 [205.74704812 30. 546.34144069 103.38247143 308.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `c`.

**Ввод**

```
[[30 25 27]
 [24, 28, 26]]

[[21 19 21]
 [19, 20, 19]]

[[18 19 20]
 [19, 18, 19]]
```



**Вывод**

```
[[30 24]
 [25 28]
 [27 26]]

[[630 475 567]
 [456 560 494]]

[[12  6  7]
 [ 5 10  7]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 9, 4, 7, 2, 8, 3, 5, 1, 0]
b = [4, 8, 3, 6, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
