# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 12

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -5 до 5.

Сделайте это двумя способами:

**Вывод**

```
array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 5×5, где первые две строки содержат значения `True`, а остальные строки содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 9×9, заполненный случайными целыми числами в интервале от 25 до 95.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении шестой строки пятого столбца
3.   Элемент на пересечении третьей строки восьмого столбца
4.   Элемент на пересечении девятой строки седьмого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[62 48 75 31 84 56 39 67 52]
 [43 79 54 68 41 85 72 36 61]
 [58 34 87 45 73 62 49 91 38]
 [76 51 42 89 55 37 64 78 46]
 [35 68 71 53 82 44 59 65 87]
 [81 47 63 74 56 92 38 51 69]
 [49 85 36 61 78 53 84 42 75]
 [67 52 84 39 65 71 46 88 54]
 [73 41 59 82 47 68 93 55 76]]
56
91
93
62
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 10.

In [ ]:
test_array = np.array([30, -20, 21, 10, -15, 40, 13, -10, 50, 12])

**Вывод**

```
array([ 30, -20,  10,  40, -10,  50])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 3, и строго меньше 10.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([2, 7, 18, 4, 10, -4, 15, 8, 11, 3])

**Вывод**

```
array([7, 4, 8, 3])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 10, на `100`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([30, -20, 21, 10, -15, 40, 13, -10, 50, 12])
```

**Вывод:**

```
array([100, 100,  21, 100, -15, 100,  13, 100, 100,  12])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[38 65 51 74 57]
 [62 44 79 55 71]
 [59 48 67 53 76]]
Количество элементов массива, меньших значения середины интервала от a1 до a2: 6
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 13·x² + 10·cos(x) + 9·exp(-x/20)

Запрограммируйте функцию с использованием возможностей numpy

`y = 13*x**2 + 10*cos(x) + 9*exp(-x/20)`

Создайте массив 7×2 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]]
```

**Вывод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]]
---------------
[[58.74704812 19.38247143]
 [119.06019121  9.        ]
 [210.34144069 58.74704812]
 [19.38247143 119.06019121]
 [ 9.        210.34144069]
 [58.74704812  9.        ]
 [119.06019121 19.38247143]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[9 4 6]
 [3, 7, 5]]

[[2 4]
 [3, 1]
 [5, 2]]

[[1 2 3]
 [2, 1, 3]]
```



**Вывод**

```
[[9 3]
 [4 7]
 [6 5]]

[[60 52]
 [52 29]]

[[ 9  8 18]
 [ 6  7 15]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 8, 5, 6, 9, 2, 7, 4, 1, 0]
b = [2, 7, 6, 9, 5, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
