# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 20

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -18 до -8.

Сделайте это двумя способами:

**Вывод**

```
array([-18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 8×8, где первые пять столбцов содержат значения `False`, а остальные столбцы содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 4×4, заполненный случайными целыми числами в интервале от 75 до 125.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении второй строки третьего столбца
3.   Элемент на пересечении четвёртой строки первого столбца
4.   Элемент на пересечении первой строки четвёртого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[98 76 105 82]
 [89 112 94 77]
 [103 85 118 91]
 [87 109 79 114]]
94
87
82
98
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 18.

In [ ]:
test_array = np.array([54, -36, 37, 18, -23, 72, 21, -18, 90, 20])

**Вывод**

```
array([ 54, -36,  18,  72, -18,  90])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 9, и строго меньше 16.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([8, 15, 26, 12, 16, -12, 23, 15, 20, 13])

**Вывод**

```
array([15, 12, 15, 13])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 18, на `180`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([54, -36, 37, 18, -23, 72, 21, -18, 90, 20])
```

**Вывод:**

```
array([180, 180,  37, 180, -23, 180,  21, 180, 180,  20])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, равных или меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[63 89 75 98 81]
 [86 68 103 79 95]
 [83 72 91 77 100]]
Количество элементов массива, равных или меньших значения середины интервала от a1 до a2: 8
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 21·x² + 18·cos(x) + 17·exp(-x/60)

Запрограммируйте функцию с использованием возможностей numpy

`y = 21*x**2 + 18*cos(x) + 17*exp(-x/60)`

Создайте массив 6×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]]
```

**Вывод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]]
---------------
[[114.74704812 51.38247143 191.06019121]
 [17.        338.34144069 114.74704812]
 [51.38247143 191.06019121 17.        ]
 [338.34144069 114.74704812 51.38247143]
 [191.06019121 17.        338.34144069]
 [114.74704812 51.38247143 17.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `c`.

**Ввод**

```
[[17 12 14]
 [11, 15, 13]]

[[8 7 9]
 [6, 8, 7]]

[[5 6 7]
 [6, 5, 6]]
```



**Вывод**

```
[[17 11]
 [12 15]
 [14 13]]

[[136  84 126]
 [ 66 120  91]]

[[12  6  7]
 [ 5 10  7]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 8, 5, 6, 9, 2, 7, 4, 1, 0]
b = [2, 7, 6, 9, 5, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
