# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 35

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от 10 до 18.

Сделайте это двумя способами:

**Вывод**

```
array([10, 11, 12, 13, 14, 15, 16, 17, 18])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 5×5, заполненный значениями `False`.
Установите значения `True` для всех элементов в четных строках (0, 2, 4).

*Подсказка:* создайте массив из нулей, приведите тип к `bool` и используйте срезы.

**Вывод**

```
array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 4*4, заполненный случайными целыми числами в интервале от 10 до 50.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении первой строки первого столбца
3.   Элемент на пересечении второй строки третьего столбца
4.   Элемент на пересечении четвертой строки второго столбца
5.   Последний элемент массива

**Вывод (случайный массив)**

```
[[23 45 12 38]
 [15 29 41 19]
 [33 10 27 49]
 [11 36 14 22]]
23
41
36
22
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите отрицательные элементы этого массива.

In [ ]:
test_array = np.array([-5, 10, -3, 0, 8, -1, 12, -8, 4, -2])

**Вывод**

```
array([-5, -3, -1, -8, -2])
```



In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 4, и меньше или равны 8.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([3, 6, 9, 4, 7, 2, 8, 5, 1, 10])

**Вывод**

```
array([6, 4, 7, 8, 5])
```



In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, которые больше 10, на значение `10`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([12, 3, 5, 15, 2, 8, 20, 1, 9, 11])
```

**Вывод:**

```
array([10,  3,  5, 10,  2,  8, 10,  1,  9, 10])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[97 88 71 63 62]
 [92 64 50 80 50]
 [92 64 93 51 57]
 [78 50 95 66 55]
 [54 50 96 64 55]]
Количество элементов массива, меньших значения середины интервала от a1 до a2: 16
```



In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = x^2 - 2 sin(x) + 1

Запрограммируйте функцию с использованием возможностей numpy

`y = x^2 - 2 sin(x) + 1`

Создайте массив 3*3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[6 4 8]
 [7 1 8]
 [3 5 5]]
```

**Вывод:**

```
[[6 4 8]
 [7 1 8]
 [3 5 5]]
---------------
[[3.55705630e+01 1.51436621e+01 6.97893658e+01]
 [5.03471140e+01 1.31705801e+00 6.97893658e+01]
 [8.71790320e+00 2.59590618e+01 2.59590618e+01]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n*m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n*m. Выведите на экран результат поэлементного вычитания матриц `a` и `b`.
3. Создайте матрицу `c` размером n*m. Выведите на экран результат поэлементного деления матриц `a` и `c`.

**Ввод**

```
[[1 2 3]
 [0 1 4]]

[[2 3 1]
 [0 1 2]]

[[4 1 4]
 [2 2 1]]
```



**Вывод**

```
[[1 0]
 [2 1]
 [3 4]]

[[-1 -1  2]
 [ 0  0  2]]

[[0.25 2.   0.75]
 [0.   0.5  4.  ]]
```



In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если сумма элементов первого и второго массива на соответствующей позиции является четным числом. В противной случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [7, 3, 5, 9, 2, 5, 4, 8, 9, 0]
b = [2, 8, 6, 7, 1, 3, 2, 9, 5, 1]

```

**Вывод:**

```
[False, True, True, False, True, False, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
