# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 4

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -2 до 6.

Сделайте это двумя способами:

**Вывод**

```
array([-2, -1,  0,  1,  2,  3,  4,  5,  6])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6 со всеми значениями, равными `True`.

*Подсказка:* создайте массив из единиц и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 4×4, заполненный случайными целыми числами в интервале от 25 до 85.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении первой строки первого столбца
3.   Элемент на пересечении третьей строки второго столбца
4.   Элемент на пересечении четвёртой строки четвёртого столбца
5.   Последний элемент массива

**Вывод (случайный массив)**

```
[[52 68 31 77]
 [43 59 82 36]
 [71 48 65 29]
 [54 37 73 61]]
52
48
61
61
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите нечётные элементы этого массива.

In [ ]:
test_array = np.array([15, -8, 11, 4, -7, 10, 9, -3, 14, 5])

**Вывод**

```
array([15, 11, -7,  9, -3,  5])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 1, и строго меньше 8.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([0, 5, 12, 2, 7, 3, 9, 1, 8, 6])

**Вывод**

```
array([5, 2, 7, 3, 1, 6])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените нечётные элементы из массива `test_array` на `-5`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([15, -8, 11, 4, -7, 10, 9, -3, 14, 5])
```

**Вывод:**

```
array([ -5,  -8,  -5,   4,  -5,  10,  -5,  -5,  14,  -5])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[18 42 31 55 27]
 [36 49 22 58 33]
 [44 25 51 38 29]]
Количество элементов массива, строго меньших значения середины интервала от a1 до a2: 8
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 5·x² + 2·cos(x) + 4·exp(-x/6)

Запрограммируйте функцию с использованием возможностей numpy

`y = 5*x**2 + 2*cos(x) + 4*exp(-x/6)`

Создайте массив 2×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[1 3 0 2 4]
 [3 1 4 0 2]]
```

**Вывод:**

```
[[1 3 0 2 4]
 [3 1 4 0 2]]
---------------
[[ 6.38247143 46.06019121  4.         22.87352406 82.34144069]
 [46.06019121  6.38247143 82.34144069  4.         22.87352406]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[5 2 3]
 [1 4 6]]

[[2 4]
 [3 1]
 [1 2]]

[[1 3 2]
 [3 1 1]]
```



**Вывод**

```
[[5 1]
 [2 4]
 [3 6]]

[[19 28]
 [20 20]]

[[ 5  6  6]
 [ 3  4  6]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 6, 5, 8, 1, 4, 7, 2, 9, 0]
b = [2, 5, 6, 7, 3, 8, 4, 9, 6, 4]

```

**Вывод:**

```
[True, False, False, False, False, True, True, True, True, True]
```

In [ ]:
# ваш код в этой ячейке
