# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 16

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -14 до -4.

Сделайте это двумя способами:

**Вывод**

```
array([-14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 4×4, где первые две строки содержат значения `True`, а последние две строки содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 7×7, заполненный случайными целыми числами в интервале от 55 до 105.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении четвёртой строки пятого столбца
3.   Элемент на пересечении второй строки седьмого столбца
4.   Элемент на пересечении седьмой строки третьего столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[82 59 87 64 96 51 73]
 [68 94 56 79 45 91 88]
 [95 52 71 58 83 66 47]
 [55 87 74 99 62 48 85]
 [76 53 92 46 69 84 57]
 [89 61 48 85 72 93 54]
 [63 78 55 91 67 49 86]]
62
88
55
82
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 14.

In [ ]:
test_array = np.array([42, -28, 29, 14, -19, 56, 17, -14, 70, 16])

**Вывод**

```
array([ 42, -28,  14,  56, -14,  70])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 7, и строго меньше 14.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([6, 11, 22, 8, 14, -8, 19, 12, 16, 9])

**Вывод**

```
array([11, 8, 12, 9])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 14, на `140`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([42, -28, 29, 14, -19, 56, 17, -14, 70, 16])
```

**Вывод:**

```
array([140, 140,  29, 140, -19, 140,  17, 140, 140,  16])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, больших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[51 77 63 86 69]
 [74 56 91 67 83]
 [71 60 79 65 88]]
Количество элементов массива, больших значения середины интервала от a1 до a2: 10
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 17·x² + 14·cos(x) + 13·exp(-x/40)

Запрограммируйте функцию с использованием возможностей numpy

`y = 17*x**2 + 14*cos(x) + 13*exp(-x/40)`

Создайте массив 2×10 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4 1 2 3 0 4]
 [1 3 0 4 2 3 1 0 4 2]]
```

**Вывод:**

```
[[2 1 3 0 4 1 2 3 0 4]
 [1 3 0 4 2 3 1 0 4 2]]
---------------
[[86.74704812 35.38247143 155.06019121 13. 274.34144069 35.38247143 86.74704812 155.06019121 13. 274.34144069]
 [35.38247143 155.06019121 13. 274.34144069 86.74704812 155.06019121 35.38247143 13. 274.34144069 86.74704812]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного возведения в степень** матрицы `a` в степень элементов матрицы `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного остатка от деления** матриц `a` и `c`.

**Ввод**

```
[[13 8 10]
 [7, 11, 9]]

[[2 1 2]
 [1, 2, 1]]

[[4 3 5]
 [3, 4, 3]]
```



**Вывод**

```
[[13 7]
 [8 11]
 [10 9]]

[[169   8 100]
 [  7 121   9]]

[[1. 2. 0.]
 [1. 3. 0.]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 8, 5, 6, 9, 2, 7, 4, 1, 0]
b = [2, 7, 6, 9, 5, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
