# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 17

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -15 до -5.

Сделайте это двумя способами:

**Вывод**

```
array([-15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 5×5, где первые три столбца содержат значения `True`, а остальные столбцы содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 8×8, заполненный случайными целыми числами в интервале от 60 до 110.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении пятой строки шестого столбца
3.   Элемент на пересечении третьей строки второго столбца
4.   Элемент на пересечении восьмой строки седьмого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[85 62 91 68 99 54 76 83]
 [71 97 59 82 48 94 65 91]
 [98 55 74 61 86 69 50 78]
 [58 90 77 102 65 51 88 67]
 [79 56 95 49 72 87 57 84]
 [92 64 51 88 75 96 53 70]
 [66 81 54 93 68 52 89 75]
 [87 63 78 55 91 74 98 62]]
87
55
98
85
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 15.

In [ ]:
test_array = np.array([45, -30, 31, 15, -20, 60, 18, -15, 75, 17])

**Вывод**

```
array([ 45, -30,  15,  60, -15,  75])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 6, и меньше или равны 13.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([5, 12, 23, 9, 13, -9, 20, 13, 17, 10])

**Вывод**

```
array([12, 9, 13, 13, 10])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 15, на `150`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([45, -30, 31, 15, -20, 60, 18, -15, 75, 17])
```

**Вывод:**

```
array([150, 150,  31, 150, -20, 150,  18, 150, 150,  17])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, меньших или равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[54 80 66 89 72]
 [77 59 94 70 86]
 [74 63 82 68 91]]
Количество элементов массива, меньших или равных значению середины интервала от a1 до a2: 6
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 18·x² + 15·sin(x) + 14·exp(-x/45)

Запрограммируйте функцию с использованием возможностей numpy

`y = 18*x**2 + 15*sin(x) + 14*exp(-x/45)`

Создайте массив 3×6 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4 1]
 [2 3 0 4 2 3]
 [1 0 4 2 3 1]]
```

**Вывод:**

```
[[2 1 3 0 4 1]
 [2 3 0 4 2 3]
 [1 0 4 2 3 1]]
---------------
[[93.74704812 39.38247143 164.06019121 14. 290.34144069 39.38247143]
 [93.74704812 164.06019121 14. 290.34144069 93.74704812 164.06019121]
 [39.38247143 14. 290.34144069 93.74704812 164.06019121 39.38247143]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `c`.

**Ввод**

```
[[14 9 11]
 [8, 12, 10]]

[[5 4 6]
 [3, 5, 4]]

[[2 3 4]
 [3, 2, 5]]
```



**Вывод**

```
[[14 8]
 [9 12]
 [11 10]]

[[19 13 17]
 [11 17 14]]

[[28 27 44]
 [24 24 50]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 9, 4, 7, 2, 8, 3, 5, 1, 0]
b = [4, 8, 3, 6, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
