# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 19

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -17 до -7.

Сделайте это двумя способами:

**Вывод**

```
array([-17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 7×7, где первые три строки содержат значения `True`, а остальные строки содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 10×10, заполненный случайными целыми числами в интервале от 70 до 120.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении седьмой строки восьмого столбца
3.   Элемент на пересечении пятой строки четвёртого столбца
4.   Элемент на пересечении десятой строки десятого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[91 68 97 74 105 60 82 89 94 73]
 [77 103 65 88 54 100 71 97 76 85]
 [104 61 80 67 92 75 56 84 85 78]
 [64 96 83 108 71 57 94 73 74 82]
 [85 62 101 55 78 93 63 90 70 88]
 [98 70 57 94 81 102 59 76 91 71]
 [72 87 60 99 74 58 95 81 81 79]
 [93 69 84 61 97 80 58 95 68 86]
 [75 90 66 100 72 80 104 68 98 74]
 [88 73 89 65 94 83 77 102 71 96]]
81
55
96
91
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 17.

In [ ]:
test_array = np.array([51, -34, 35, 17, -22, 68, 20, -17, 85, 19])

**Вывод**

```
array([ 51, -34,  17,  68, -17,  85])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 7, и меньше или равны 14.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([6, 14, 25, 11, 14, -11, 22, 14, 19, 12])

**Вывод**

```
array([14, 11, 14, 14, 12])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 17, на `170`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([51, -34, 35, 17, -22, 68, 20, -17, 85, 19])
```

**Вывод:**

```
array([170, 170,  35, 170, -22, 170,  20, 170, 170,  19])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго больших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[60 86 72 95 78]
 [83 65 100 76 92]
 [80 69 88 74 97]]
Количество элементов массива, строго больших значения середины интервала от a1 до a2: 9
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 20·x² + 17·sin(x) + 16·exp(-x/55)

Запрограммируйте функцию с использованием возможностей numpy

`y = 20*x**2 + 17*sin(x) + 16*exp(-x/55)`

Создайте массив 5×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]]
---------------
[[107.74704812 47.38247143 182.06019121 16.        ]
 [322.34144069 107.74704812 47.38247143 182.06019121]
 [16.        182.06019121 107.74704812 322.34144069]
 [47.38247143 16.        322.34144069 107.74704812]
 [182.06019121 322.34144069 16.         47.38247143]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного остатка от деления** матриц `a` и `c`.

**Ввод**

```
[[16 11 13]
 [10, 14, 12]]

[[7 6 8]
 [5, 7, 6]]

[[4 5 6]
 [5, 4, 5]]
```



**Вывод**

```
[[16 10]
 [11 14]
 [13 12]]

[[23 17 21]
 [15 21 18]]

[[0. 1. 1.]
 [0. 2. 2.]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
