# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 15

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -13 до -3.

Сделайте это двумя способами:

**Вывод**

```
array([-13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 8×8, где первые пять столбцов содержат значения `False`, а остальные столбцы содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True],
       [False, False, False, False, False,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 6×6, заполненный случайными целыми числами в интервале от 50 до 100.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении третьей строки третьего столбца
3.   Элемент на пересечении шестой строки шестого столбца
4.   Элемент на пересечении первой строки пятого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[78 54 82 61 93 47]
 [65 89 53 76 42 88]
 [91 47 68 55 79 63]
 [52 84 71 96 58 45]
 [73 56 87 49 64 81]
 [69 75 54 83 72 97]]
68
97
93
78
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 13.

In [ ]:
test_array = np.array([39, -26, 27, 13, -18, 52, 16, -13, 65, 15])

**Вывод**

```
array([ 39, -26,  13,  52, -13,  65])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 5, и меньше или равны 12.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([4, 10, 21, 7, 12, -7, 18, 11, 15, 8])

**Вывод**

```
array([10, 7, 12, 11, 8])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 13, на `130`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([39, -26, 27, 13, -18, 52, 16, -13, 65, 15])
```

**Вывод:**

```
array([130, 130,  27, 130, -18, 130,  16, 130, 130,  15])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[48 74 60 83 66]
 [71 53 88 64 80]
 [68 57 76 62 85]]
Количество элементов массива, строго меньших значения середины интервала от a1 до a2: 7
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 16·x² + 13·sin(x) + 12·exp(-x/35)

Запрограммируйте функцию с использованием возможностей numpy

`y = 16*x**2 + 13*sin(x) + 12*exp(-x/35)`

Создайте массив 10×2 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]
 [4 2]
 [1 0]
 [2 3]]
```

**Вывод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]
 [4 2]
 [1 0]
 [2 3]]
---------------
[[79.74704812 31.38247143]
 [146.06019121 12.        ]
 [258.34144069 79.74704812]
 [31.38247143 146.06019121]
 [12.        258.34144069]
 [79.74704812 12.        ]
 [146.06019121 31.38247143]
 [258.34144069 79.74704812]
 [31.38247143 12.        ]
 [79.74704812 146.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `c`.

**Ввод**

```
[[12 7 9]
 [6, 10, 8]]

[[4 3 5]
 [2, 4, 3]]

[[3 2 4]
 [2, 3, 2]]
```



**Вывод**

```
[[12 6]
 [7 10]
 [9 8]]

[[48 21 45]
 [12 40 24]]

[[4.  3.5 2.25]
 [3.  3.33333333 4.  ]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
