# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 9

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -7 до 4.

Сделайте это двумя способами:

**Вывод**

```
array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6 со всеми значениями, равными `False`.

*Подсказка:* создайте массив из нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 6×4, заполненный случайными целыми числами в интервале от 45 до 99.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении первой строки второго столбца
3.   Элемент на пересечении третьей строки четвёртого столбца
4.   Элемент на пересечении шестой строки первого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[72 58 84 61]
 [49 93 67 52]
 [88 46 75 91]
 [54 82 48 79]
 [63 57 86 45]
 [97 51 73 68]]
58
91
97
72
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 7.

In [ ]:
test_array = np.array([21, -14, 15, 7, -10, 28, 9, -7, 35, 8])

**Вывод**

```
array([ 21, -14,   7,  28,  -7,  35])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 1, и меньше или равны 8.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([0, 5, 15, 2, 8, -1, 9, 6, 7, 1])

**Вывод**

```
array([5, 2, 8, 6, 7])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 7, на `70`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([21, -14, 15, 7, -10, 28, 9, -7, 35, 8])
```

**Вывод:**

```
array([70, 70, 15, 70, -10, 70,  9, 70, 70,  8])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не превышающих значение середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[35 62 48 71 54]
 [59 41 77 52 68]
 [56 45 64 50 73]]
Количество элементов массива, не превышающих значение середины интервала от a1 до a2: 8
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 10·x² + 7·sin(x) + 6·exp(-x/12)

Запрограммируйте функцию с использованием возможностей numpy

`y = 10*x**2 + 7*sin(x) + 6*exp(-x/12)`

Создайте массив 4×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]]
---------------
[[43.74704812 13.38247143 92.06019121  6.        ]
 [162.34144069 43.74704812 13.38247143 92.06019121]
 [ 6.         92.06019121 43.74704812 162.34144069]
 [13.38247143  6.        162.34144069 43.74704812]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[5 3 2]
 [1, 4, 6]]

[[3 2]
 [1, 4]
 [2, 1]]

[[2 1 3]
 [3, 2, 1]]
```



**Вывод**

```
[[5 1]
 [3 4]
 [2 6]]

[[22 24]
 [19 42]]

[[10  3  6]
 [ 3  8  6]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 7, 4, 9, 2, 8, 3, 5, 1, 0]
b = [4, 6, 3, 8, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
