# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 5

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -4 до 4.

Сделайте это двумя способами:

**Вывод**

```
array([-4, -3, -2, -1,  0,  1,  2,  3,  4])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 3×3 со всеми значениями, равными `False`.

*Подсказка:* создайте массив из нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False],
       [False, False, False],
       [False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 5×5, заполненный случайными целыми числами в интервале от 30 до 90.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении второй строки третьего столбца
3.   Элемент на пересечении первой строки пятого столбца
4.   Элемент на пересечении пятой строки второго столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[48 72 35 61 89]
 [56 43 78 52 67]
 [39 85 44 71 58]
 [63 37 82 49 75]
 [54 68 41 86 33]]
78
89
68
48
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 3.

In [ ]:
test_array = np.array([9, -6, 11, 3, -8, 12, 7, -9, 15, 4])

**Вывод**

```
array([ 9, -6,  3, 12, -9, 15])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 0, и меньше или равны 5.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([-2, 3, 7, 1, 5, 0, 6, 4, 8, 2])

**Вывод**

```
array([3, 1, 5, 4, 2])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 3, на `50`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([9, -6, 11, 3, -8, 12, 7, -9, 15, 4])
```

**Вывод:**

```
array([50, 50, 11, 50, -8, 50,  7, 50, 50,  4])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не превышающих значение середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[22 48 35 57 41]
 [39 52 28 61 33]
 [45 31 54 37 49]]
Количество элементов массива, не превышающих значение середины интервала от a1 до a2: 9
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 6·x² + 3·sin(x) + 2·exp(-x/4)

Запрограммируйте функцию с использованием возможностей numpy

`y = 6*x**2 + 3*sin(x) + 2*exp(-x/4)`

Создайте массив 3×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 0 3 1]
 [4 2 0 3]
 [1 3 4 0]]
```

**Вывод:**

```
[[2 0 3 1]
 [4 2 0 3]
 [1 3 4 0]]
---------------
[[25.74704812  2.         55.65892427  7.90824351]
 [97.81859485 25.74704812  2.         55.65892427]
 [ 7.90824351 55.65892427 97.81859485  2.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[2 4 1]
 [3 1 5]]

[[1 2]
 [3 1]
 [2 4]]

[[3 1 2]
 [1 2 3]]
```



**Вывод**

```
[[2 3]
 [4 1]
 [1 5]]

[[16 12]
 [16 27]]

[[ 6  4  2]
 [ 3  2 15]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [2, 7, 4, 9, 6, 1, 8, 3, 5, 0]
b = [1, 6, 3, 8, 5, 4, 7, 2, 9, 3]

```

**Вывод:**

```
[True, False, True, False, True, True, True, False, False, False]
```

In [ ]:
# ваш код в этой ячейке
