# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 13

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -11 до -1.

Сделайте это двумя способами:

**Вывод**

```
array([-11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6, где первые три столбца содержат значения `True`, а остальные столбцы содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 10×10, заполненный случайными целыми числами в интервале от 30 до 100.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении седьмой строки шестого столбца
3.   Элемент на пересечении четвёртой строки девятого столбца
4.   Элемент на пересечении десятой строки восьмого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[72 58 84 61 49 93 67 52 88 46]
 [75 91 54 68 41 85 72 36 61 79]
 [58 34 87 45 73 62 49 91 38 65]
 [76 51 42 89 55 37 64 78 46 83]
 [35 68 71 53 82 44 59 65 87 52]
 [81 47 63 74 56 92 38 51 69 74]
 [49 85 36 61 78 53 84 42 75 68]
 [67 52 84 39 65 71 46 88 54 91]
 [73 41 59 82 47 68 93 55 76 48]
 [56 79 45 68 83 54 71 62 89 57]]
53
78
62
72
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 11.

In [ ]:
test_array = np.array([33, -22, 23, 11, -16, 44, 14, -11, 55, 13])

**Вывод**

```
array([ 33, -22,  11,  44, -11,  55])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 4, и меньше или равны 11.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([3, 8, 19, 5, 11, -5, 16, 9, 12, 4])

**Вывод**

```
array([8, 5, 11, 9])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 11, на `110`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([33, -22, 23, 11, -16, 44, 14, -11, 55, 13])
```

**Вывод:**

```
array([110, 110,  23, 110, -16, 110,  14, 110, 110,  13])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, больших или равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[42 68 54 77 60]
 [65 47 82 58 74]
 [62 51 70 56 79]]
Количество элементов массива, больших или равных значению середины интервала от a1 до a2: 11
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 14·x² + 11·sin(x) + 10·exp(-x/25)

Запрограммируйте функцию с использованием возможностей numpy

`y = 14*x**2 + 11*sin(x) + 10*exp(-x/25)`

Создайте массив 8×2 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]
 [4 2]]
```

**Вывод:**

```
[[2 1]
 [3 0]
 [4 2]
 [1 3]
 [0 4]
 [2 0]
 [3 1]
 [4 2]]
---------------
[[65.74704812 23.38247143]
 [128.06019121 10.        ]
 [226.34144069 65.74704812]
 [23.38247143 128.06019121]
 [10.        226.34144069]
 [65.74704812 10.        ]
 [128.06019121 23.38247143]
 [226.34144069 65.74704812]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[10 5 7]
 [4, 8, 6]]

[[3 2]
 [4, 1]
 [6, 3]]

[[2 1 3]
 [3, 2, 1]]
```



**Вывод**

```
[[10 4]
 [5 8]
 [7 6]]

[[92 46]
 [80 34]]

[[20  5 21]
 [12 16  6]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 9, 4, 7, 2, 8, 3, 5, 1, 0]
b = [4, 8, 3, 6, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
