# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 25

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -23 до -13.

Сделайте это двумя способами:

**Вывод**

```
array([-23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6, где первые четыре строки содержат значения `True`, а остальные строки содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 9×9, заполненный случайными целыми числами в интервале от 100 до 150.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении седьмой строки девятого столбца
3.   Элемент на пересечении четвёртой строки седьмого столбца
4.   Элемент на пересечении девятой строки третьего столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[133 111 140 117 124 126 135 138 141]
 [124 147 129 112 131 133 142 149 145]
 [138 120 150 126 115 129 149 150 148]
 [122 135 113 144 119 136 145 145 148]
 [130 116 142 123 134 118 150 150 147]
 [128 121 139 125 148 132 117 150 146]
 [136 119 146 127 141 150 143 143 149]
 [144 123 150 128 137 147 140 146 149]
 [142 125 148 130 139 145 141 144 147]]
149
145
148
133
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 23.

In [ ]:
test_array = np.array([69, -46, 47, 23, -28, 92, 26, -23, 115, 25])

**Вывод**

```
array([ 69, -46,  23,  92, -23, 115])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 10, и меньше или равны 17.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([9, 20, 31, 17, 17, -17, 28, 17, 25, 16])

**Вывод**

```
array([17, 17, 17, 16])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 23, на `230`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([69, -46, 47, 23, -28, 92, 26, -23, 115, 25])
```

**Вывод:**

```
array([230, 230,  47, 230, -28, 230,  26, 230, 230,  25])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[78 104 90 113 96]
 [101 83 118 94 110]
 [98 87 106 92 115]]
Количество элементов массива, равных значению середины интервала от a1 до a2: 1
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 26·x² + 23·sin(x) + 22·exp(-x/85)

Запрограммируйте функцию с использованием возможностей numpy

`y = 26*x**2 + 23*sin(x) + 22*exp(-x/85)`

Создайте массив 4×6 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4 1]
 [2 3 0 4 2 3]
 [1 0 4 2 3 1]
 [3 4 0 1 2 0]]
```

**Вывод:**

```
[[2 1 3 0 4 1]
 [2 3 0 4 2 3]
 [1 0 4 2 3 1]
 [3 4 0 1 2 0]]
---------------
[[149.74704812 71.38247143 236.06019121 22. 418.34144069 71.38247143]
 [149.74704812 236.06019121 22. 418.34144069 149.74704812 236.06019121]
 [71.38247143 22. 418.34144069 149.74704812 236.06019121 71.38247143]
 [236.06019121 418.34144069 22. 71.38247143 149.74704812 22.]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `c`.

**Ввод**

```
[[22 17 19]
 [16, 20, 18]]

[[13 11 13]
 [11, 12, 11]]

[[10 11 12]
 [11, 10, 11]]
```



**Вывод**

```
[[22 16]
 [17 20]
 [19 18]]

[[ 9  6  6]
 [ 5  8  7]]

[[220 187 228]
 [176 200 198]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 9, 4, 7, 2, 8, 3, 5, 1, 0]
b = [4, 8, 3, 6, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
