# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 31

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -29 до -19.

Сделайте это двумя способами:

**Вывод**

```
array([-29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 5×5, где первые три столбца содержат значения `True`, а остальные столбцы содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 8×8, заполненный случайными целыми числами в интервале от 130 до 180.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении шестой строки восьмого столбца
3.   Элемент на пересечении четвёртой строки второго столбца
4.   Элемент на пересечении восьмой строки шестого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[175 153 180 157 164 171 177 183]
 [166 189 171 154 173 180 186 186]
 [180 162 178 168 175 182 188 188]
 [173 158 183 165 176 176 182 182]
 [171 155 181 165 183 183 189 189]
 [171 164 181 170 184 184 190 190]
 [171 164 181 170 184 184 190 190]
 [171 164 181 170 184 184 190 190]]
190
158
184
175
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 29.

In [ ]:
test_array = np.array([87, -58, 59, 29, -34, 116, 32, -29, 145, 31])

**Вывод**

```
array([ 87, -58,  29, 116, -29, 145])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 13, и меньше или равны 20.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([12, 26, 37, 20, 20, -23, 34, 20, 31, 19])

**Вывод**

```
array([20, 20, 20, 19])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 29, на `290`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([87, -58, 59, 29, -34, 116, 32, -29, 145, 31])
```

**Вывод:**

```
array([290, 290,  59, 290, -34, 290,  32, 290, 290,  31])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, меньших или равных значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[96 122 108 131 114]
 [119 101 136 112 128]
 [116 105 124 110 133]]
Количество элементов массива, меньших или равных значения середины интервала от a1 до a2: 8
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 32·x² + 29·sin(x) + 28·exp(-x/115)

Запрограммируйте функцию с использованием возможностей numpy

`y = 32*x**2 + 29*sin(x) + 28*exp(-x/115)`

Создайте массив 10×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]
 [1 2 0 3]
 [3 0 4 2]
 [2 1 0 3]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]
 [1 2 0 3]
 [3 0 4 2]
 [2 1 0 3]]
---------------
[[191.74704812 95.38247143 290.06019121 28.        ]
 [514.34144069 191.74704812 95.38247143 290.06019121]
 [28.        290.06019121 191.74704812 514.34144069]
 [95.38247143 28.        514.34144069 191.74704812]
 [290.06019121 514.34144069 28.         95.38247143]
 [191.74704812 28.         95.38247143 290.06019121]
 [514.34144069 290.06019121 191.74704812 28.        ]
 [95.38247143 191.74704812 28.        290.06019121]
 [290.06019121 28.        514.34144069 191.74704812]
 [191.74704812 95.38247143 28.        290.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного остатка от деления** матриц `a` и `c`.

**Ввод**

```
[[28 23 25]
 [22, 26, 24]]

[[19 17 19]
 [17, 18, 17]]

[[16 17 18]
 [17, 16, 17]]
```



**Вывод**

```
[[28 22]
 [23 26]
 [25 24]]

[[ 9  6  6]
 [ 5  8  7]]

[[12.  6.  7.]
 [ 5. 10.  7.]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
