# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 18

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -16 до -6.

Сделайте это двумя способами:

**Вывод**

```
array([-16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 6×6, где первые четыре столбца содержат значения `False`, а остальные столбцы содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True],
       [False, False, False, False,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 9×9, заполненный случайными целыми числами в интервале от 65 до 115.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении шестой строки седьмого столбца
3.   Элемент на пересечении четвёртой строки третьего столбца
4.   Элемент на пересечении девятой строки девятого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[88 65 94 71 102 57 79 86 91]
 [74 100 62 85 51 97 68 94 73]
 [101 58 77 64 89 72 53 81 82]
 [61 93 80 105 68 54 91 70 71]
 [82 59 98 52 75 90 60 87 67]
 [95 67 54 91 78 99 56 73 88]
 [69 84 57 96 71 55 92 78 78]
 [90 66 81 58 94 77 55 92 65]
 [72 87 63 97 69 77 101 65 95]]
56
80
95
88
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 16.

In [ ]:
test_array = np.array([48, -32, 33, 16, -21, 64, 19, -16, 80, 18])

**Вывод**

```
array([ 48, -32,  16,  64, -16,  80])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 8, и строго меньше 15.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([7, 13, 24, 10, 15, -10, 21, 14, 18, 11])

**Вывод**

```
array([13, 10, 14, 11])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 16, на `160`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([48, -32, 33, 16, -21, 64, 19, -16, 80, 18])
```

**Вывод:**

```
array([160, 160,  33, 160, -21, 160,  19, 160, 160,  18])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не превышающих значение середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[57 83 69 92 75]
 [80 62 97 73 89]
 [77 66 85 71 94]]
Количество элементов массива, не превышающих значение середины интервала от a1 до a2: 7
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 19·x² + 16·cos(x) + 15·exp(-x/50)

Запрограммируйте функцию с использованием возможностей numpy

`y = 19*x**2 + 16*cos(x) + 15*exp(-x/50)`

Создайте массив 4×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 0 4 1 2]]
```

**Вывод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 0 4 1 2]]
---------------
[[100.74704812 43.38247143 173.06019121 15. 306.34144069]
 [43.38247143 100.74704812 15. 173.06019121 306.34144069]
 [15. 173.06019121 100.74704812 306.34144069 43.38247143]
 [173.06019121 15. 306.34144069 43.38247143 100.74704812]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `c`.

**Ввод**

```
[[15 10 12]
 [9, 13, 11]]

[[6 5 7]
 [4, 6, 5]]

[[3 4 5]
 [4, 3, 4]]
```



**Вывод**

```
[[15 9]
 [10 13]
 [12 11]]

[[ 9  5  5]
 [ 5  7  6]]

[[5.  2.5 2.4]
 [2.25 4.33333333 2.75]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 9, 6, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
