# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 22

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -20 до -10.

Сделайте это двумя способами:

**Вывод**

```
array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 10×10, где первые семь столбцов содержат значения `True`, а остальные столбцы содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 6×6, заполненный случайными целыми числами в интервале от 85 до 135.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении четвёртой строки шестого столбца
3.   Элемент на пересечении первой строки третьего столбца
4.   Элемент на пересечении шестой строки четвёртого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[112 90 119 96 103 105]
 [103 126 108 91 110 112]
 [117 99 132 105 94 108]
 [101 114 92 123 98 115]
 [109 95 121 102 113 97]
 [107 100 118 104 128 125]]
115
119
104
112
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 20.

In [ ]:
test_array = np.array([60, -40, 41, 20, -25, 80, 23, -20, 100, 22])

**Вывод**

```
array([ 60, -40,  20,  80, -20, 100])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 10, и строго меньше 17.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([9, 17, 28, 14, 17, -14, 25, 17, 22, 15])

**Вывод**

```
array([14, 15])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 20, на `200`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([60, -40, 41, 20, -25, 80, 23, -20, 100, 22])
```

**Вывод:**

```
array([200, 200,  41, 200, -25, 200,  23, 200, 200,  22])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[69 95 81 104 87]
 [92 74 109 85 101]
 [89 78 97 83 106]]
Количество элементов массива, строго меньших значения середины интервала от a1 до a2: 7
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 23·x² + 20·cos(x) + 19·exp(-x/70)

Запрограммируйте функцию с использованием возможностей numpy

`y = 23*x**2 + 20*cos(x) + 19*exp(-x/70)`

Создайте массив 8×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]
 [4 3 2]
 [1 0 4]]
```

**Вывод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]
 [4 3 2]
 [1 0 4]]
---------------
[[128.74704812 59.38247143 209.06019121]
 [19.        370.34144069 128.74704812]
 [59.38247143 209.06019121 19.        ]
 [370.34144069 128.74704812 59.38247143]
 [209.06019121 19.        370.34144069]
 [128.74704812 59.38247143 19.        ]
 [370.34144069 209.06019121 128.74704812]
 [59.38247143 19.        370.34144069]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного возведения в степень** матрицы `a` в степень элементов матрицы `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `c`.

**Ввод**

```
[[19 14 16]
 [13, 17, 15]]

[[10 8 10]
 [8, 9, 8]]

[[7 8 9]
 [8, 7, 8]]
```



**Вывод**

```
[[19 13]
 [14 17]
 [16 15]]

[[6.13106626e+12 1.47578906e+09 1.09951163e+12]
 [8.15730721e+08 4.10338673e+10 3.84433594e+08]]

[[133 112 144]
 [104 119 120]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 9, 6, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
