# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 28

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -26 до -16.

Сделайте это двумя способами:

**Вывод**

```
array([-26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 9×9, где первые семь столбцов содержат значения `False`, а остальные столбцы содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True],
       [False, False, False, False, False, False, False,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 5×5, заполненный случайными целыми числами в интервале от 115 до 165.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении третьей строки пятого столбца
3.   Элемент на пересечении первой строки первого столбца
4.   Элемент на пересечении пятой строки второго столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[154 132 161 138 145]
 [145 168 150 133 152]
 [159 141 157 147 154]
 [152 137 162 144 155]
 [150 143 160 149 163]]
154
154
143
154
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 26.

In [ ]:
test_array = np.array([78, -52, 53, 26, -31, 104, 29, -26, 130, 28])

**Вывод**

```
array([ 78, -52,  26, 104, -26, 130])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 13, и строго меньше 20.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([12, 23, 34, 19, 20, -20, 31, 19, 28, 18])

**Вывод**

```
array([19, 19, 18])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 26, на `260`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([78, -52, 53, 26, -31, 104, 29, -26, 130, 28])
```

**Вывод:**

```
array([260, 260,  53, 260, -31, 260,  29, 260, 260,  28])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[87 113 99 122 105]
 [110 92 127 103 119]
 [107 96 115 101 124]]
Количество элементов массива, не меньших значения середины интервала от a1 до a2: 10
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 29·x² + 26·cos(x) + 25·exp(-x/100)

Запрограммируйте функцию с использованием возможностей numpy

`y = 29*x**2 + 26*cos(x) + 25*exp(-x/100)`

Создайте массив 7×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]]
---------------
[[170.74704812 83.38247143 263.06019121 25.        ]
 [466.34144069 170.74704812 83.38247143 263.06019121]
 [25.        263.06019121 170.74704812 466.34144069]
 [83.38247143 25.        466.34144069 170.74704812]
 [263.06019121 466.34144069 25.         83.38247143]
 [170.74704812 25.         83.38247143 263.06019121]
 [466.34144069 263.06019121 170.74704812 25.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `c`.

**Ввод**

```
[[25 20 22]
 [19, 23, 21]]

[[16 14 16]
 [14, 15, 14]]

[[13 14 15]
 [14, 13, 14]]
```



**Вывод**

```
[[25 19]
 [20 23]
 [22 21]]

[[400 280 352]
 [266 345 294]]

[[12  6  7]
 [ 5 10  7]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 8, 5, 6, 9, 2, 7, 4, 1, 0]
b = [2, 7, 6, 9, 5, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
