# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 26

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -24 до -14.

Сделайте это двумя способами:

**Вывод**

```
array([-24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 7×7, где первые пять столбцов содержат значения `True`, а остальные столбцы содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False],
       [ True,  True,  True,  True,  True, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 10×10, заполненный случайными целыми числами в интервале от 105 до 155.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении восьмой строки десятого столбца
3.   Элемент на пересечении пятой строки восьмого столбца
4.   Элемент на пересечении десятой строки шестого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[140 118 147 124 131 133 142 145 148 151]
 [131 154 136 119 138 140 149 150 152 155]
 [145 127 150 133 122 136 150 151 153 155]
 [129 142 120 151 126 143 152 152 154 155]
 [137 123 149 130 141 125 150 150 154 154]
 [135 128 146 132 150 139 124 150 153 155]
 [143 126 153 134 148 150 150 150 155 155]
 [151 130 150 135 144 154 147 153 155 155]
 [149 132 150 137 146 152 148 151 154 155]
 [150 133 150 138 147 150 150 151 154 155]]
155
150
150
140
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 24.

In [ ]:
test_array = np.array([72, -48, 49, 24, -29, 96, 27, -24, 120, 26])

**Вывод**

```
array([ 72, -48,  24,  96, -24, 120])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 12, и строго меньше 19.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([11, 21, 32, 18, 19, -18, 29, 18, 26, 17])

**Вывод**

```
array([18, 18, 17])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 24, на `240`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([72, -48, 49, 24, -29, 96, 27, -24, 120, 26])
```

**Вывод:**

```
array([240, 240,  49, 240, -29, 240,  27, 240, 240,  26])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго превышающих значение середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[81 107 93 116 99]
 [104 86 121 97 113]
 [101 90 109 95 118]]
Количество элементов массива, строго превышающих значение середины интервала от a1 до a2: 9
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 27·x² + 24·cos(x) + 23·exp(-x/90)

Запрограммируйте функцию с использованием возможностей numpy

`y = 27*x**2 + 24*cos(x) + 23*exp(-x/90)`

Создайте массив 5×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 0 4 1 2]
 [4 4 2 0 1]]
```

**Вывод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 0 4 1 2]
 [4 4 2 0 1]]
---------------
[[156.74704812 75.38247143 245.06019121 23. 434.34144069]
 [75.38247143 156.74704812 23. 245.06019121 434.34144069]
 [23. 245.06019121 156.74704812 434.34144069 75.38247143]
 [245.06019121 23. 434.34144069 75.38247143 156.74704812]
 [434.34144069 434.34144069 156.74704812 23. 75.38247143]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `c`.

**Ввод**

```
[[23 18 20]
 [17, 21, 19]]

[[14 12 14]
 [12, 13, 12]]

[[11 12 13]
 [12, 11, 12]]
```



**Вывод**

```
[[23 17]
 [18 21]
 [20 19]]

[[1.64285714 1.5 1.42857143]
 [1.41666667 1.61538462 1.58333333]]

[[34 30 33]
 [29 32 31]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 9, 6, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
