# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 30

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -28 до -18.

Сделайте это двумя способами:

**Вывод**

```
array([-28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 4×4, где первые две строки содержат значения `True`, а последние две строки содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 7×7, заполненный случайными целыми числами в интервале от 125 до 175.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении пятой строки третьего столбца
3.   Элемент на пересечении третьей строки седьмого столбца
4.   Элемент на пересечении седьмой строки пятого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[168 146 175 152 159 166 172]
 [159 182 164 147 166 173 179]
 [173 155 171 161 168 175 181]
 [166 151 176 158 169 169 175]
 [164 148 174 158 176 176 182]
 [164 157 174 163 177 177 183]
 [164 157 174 163 177 177 183]]
174
181
177
168
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 28.

In [ ]:
test_array = np.array([84, -56, 57, 28, -33, 112, 31, -28, 140, 30])

**Вывод**

```
array([ 84, -56,  28, 112, -28, 140])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 14, и строго меньше 21.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([13, 25, 36, 20, 21, -22, 33, 20, 30, 19])

**Вывод**

```
array([20, 20, 19])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 28, на `280`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([84, -56, 57, 28, -33, 112, 31, -28, 140, 30])
```

**Вывод:**

```
array([280, 280,  57, 280, -33, 280,  31, 280, 280,  30])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[93 119 105 128 111]
 [116 98 133 109 125]
 [113 102 121 107 130]]
Количество элементов массива, строго меньших значения середины интервала от a1 до a2: 7
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 31·x² + 28·cos(x) + 27·exp(-x/110)

Запрограммируйте функцию с использованием возможностей numpy

`y = 31*x**2 + 28*cos(x) + 27*exp(-x/110)`

Создайте массив 9×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]
 [1 2 0 3]
 [3 0 4 2]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]
 [1 2 0 3]
 [3 0 4 2]]
---------------
[[184.74704812 91.38247143 281.06019121 27.        ]
 [498.34144069 184.74704812 91.38247143 281.06019121]
 [27.        281.06019121 184.74704812 498.34144069]
 [91.38247143 27.        498.34144069 184.74704812]
 [281.06019121 498.34144069 27.         91.38247143]
 [184.74704812 27.         91.38247143 281.06019121]
 [498.34144069 281.06019121 184.74704812 27.        ]
 [91.38247143 184.74704812 27.        281.06019121]
 [281.06019121 27.        498.34144069 184.74704812]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного остатка от деления** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного умножения** матриц `a` и `c`.

**Ввод**

```
[[27 22 24]
 [21, 25, 23]]

[[18 16 18]
 [16, 17, 16]]

[[15 16 17]
 [16, 15, 16]]
```



**Вывод**

```
[[27 21]
 [22 25]
 [24 23]]

[[9. 6. 6.]
 [5. 8. 7.]]

[[405 352 408]
 [336 375 368]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 9, 6, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
