# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 3

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -3 до 7.

Сделайте это двумя способами:

**Вывод**

```
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 2×2 со всеми значениями, равными `False`.

*Подсказка:* создайте массив из нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False],
       [False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 6×6, заполненный случайными целыми числами в интервале от 15 до 75.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении второй строки первого столбца
3.   Элемент на пересечении первой строки шестого столбца
4.   Элемент на пересечении пятой строки четвёртого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[42 58 31 67 23 71]
 [35 49 62 18 54 39]
 [66 27 44 59 33 72]
 [21 53 38 64 47 29]
 [56 41 69 32 58 45]
 [37 63 25 51 42 68]]
35
71
32
42
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите чётные элементы этого массива.

In [ ]:
test_array = np.array([12, -7, 8, 3, -4, 9, 16, -2, 11, 6])

**Вывод**

```
array([12,  8, -4, 16, -2,  6])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 2, и меньше или равны 6.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([0, 4, 8, 3, 6, 1, 7, 5, 2, 9])

**Вывод**

```
array([4, 3, 6, 5])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените чётные элементы из массива `test_array` на `-10`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([12, -7, 8, 3, -4, 9, 16, -2, 11, 6])
```

**Вывод:**

```
array([-10,  -7, -10,   3, -10,   9, -10, -10,  11, -10])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, равных значению середины интервала от `a1` до `a2` или превышающих его.

**Вывод (случайный массив)**

```
[[28 45 33 52 41]
 [37 29 48 31 55]
 [42 35 26 49 38]]
Количество элементов массива, равных значению середины интервала от a1 до a2 или превышающих его: 9
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 4·x² + 3·sin(x) + 5·exp(-x/8)

Запрограммируйте функцию с использованием возможностей numpy

`y = 4*x**2 + 3*sin(x) + 5*exp(-x/8)`

Создайте массив 5×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 1 2 4]
 [3 0 4 1 2]
 [4 4 2 0 1]]
```

**Вывод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 1 2 4]
 [3 0 4 1 2]
 [4 4 2 0 1]]
---------------
[[18.87352406  6.90824351 38.54062922  5.         67.81859485]
 [ 6.90824351 18.87352406  5.         38.54062922 67.81859485]
 [ 5.         38.54062922  6.90824351 18.87352406 67.81859485]
 [38.54062922  5.         67.81859485  6.90824351 18.87352406]
 [67.81859485 67.81859485 18.87352406  5.          6.90824351]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[4 3 2]
 [1 5 3]]

[[3 2]
 [1 4]
 [2 1]]

[[1 2 3]
 [4 1 2]]
```



**Вывод**

```
[[4 1]
 [3 5]
 [2 3]]

[[19 22]
 [14 25]]

[[ 4  6  6]
 [ 4  5  6]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 5, 4, 7, 2, 8, 3, 9, 1, 0]
b = [5, 6, 3, 8, 4, 7, 2, 9, 5, 3]

```

**Вывод:**

```
[True, False, True, True, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
