# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 2

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от 2 до 10.

Сделайте это двумя способами:

**Вывод**

```
array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 5×5 со всеми значениями, равными `True`.

*Подсказка:* создайте массив из единиц и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 3×3, заполненный случайными целыми числами в интервале от 20 до 80.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении первой строки третьего столбца
3.   Элемент на пересечении второй строки второго столбца
4.   Элемент на пересечении третьей строки первого столбца
5.   Последний элемент массива

**Вывод (случайный массив)**

```
[[45 67 32]
 [78 54 29]
 [61 38 75]]
32
54
61
75
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите неотрицательные элементы этого массива (большие или равные нулю).

In [ ]:
test_array = np.array([-7, 2, -4, 0, 9, -1, 5, -3, 8, 0])

**Вывод**

```
array([2, 0, 9, 5, 8, 0])
```



In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 4, и строго меньше 10.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([3, 6, 11, 4, 9, 2, 10, 5, 8, 1])

**Вывод**

```
array([6, 4, 9, 5, 8])
```



In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените нечётные элементы из массива `test_array` на `100`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([-7, 2, -4, 0, 9, -1, 5, -3, 8, 0])
```

**Вывод:**

```
array([100,   2,  -4,   0, 100, 100, 100, 100,   8,   0])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго больших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[15 42 28 37 51]
 [33 19 46 25 55]
 [41 30 16 49 22]]
Количество элементов массива, строго больших значения середины интервала от a1 до a2: 7
```



In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 2·x² + 5·cos(x) + 3·exp(-x/5)

Запрограммируйте функцию с использованием возможностей numpy

`y = 2*x**2 + 5*cos(x) + 3*exp(-x/5)`

Создайте массив 3×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]]
```

**Вывод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]]
---------------
[[10.87352406  6.90824351 21.54062922]
 [ 3.         30.34144069 10.87352406]
 [ 6.90824351 21.54062922  3.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[3 2 1]
 [1 4 2]]

[[2 1]
 [3 0]
 [1 4]]

[[2 3 1]
 [4 1 2]]
```



**Вывод**

```
[[3 1]
 [2 4]
 [1 2]]

[[13  7]
 [16  9]]

[[ 6  6  1]
 [ 4  4  4]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [4, 7, 5, 8, 6, 3, 2, 9, 3, 2]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
