# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 29

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -27 до -17.

Сделайте это двумя способами:

**Вывод**

```
array([-27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 10×10, где первые восемь строк содержат значения `True`, а остальные строки содержат значения `False`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 6×6, заполненный случайными целыми числами в интервале от 120 до 170.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении четвёртой строки четвёртого столбца
3.   Элемент на пересечении второй строки шестого столбца
4.   Элемент на пересечении шестой строки первого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[161 139 168 145 152 159]
 [152 175 157 140 159 166]
 [166 148 164 154 161 168]
 [159 144 169 151 162 162]
 [157 141 167 151 169 169]
 [157 150 167 156 170 170]]
151
166
157
161
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 27.

In [ ]:
test_array = np.array([81, -54, 55, 27, -32, 108, 30, -27, 135, 29])

**Вывод**

```
array([ 81, -54,  27, 108, -27, 135])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 12, и меньше или равны 19.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([11, 24, 35, 19, 19, -21, 32, 19, 29, 18])

**Вывод**

```
array([19, 19, 19, 18])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 27, на `270`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([81, -54, 55, 27, -32, 108, 30, -27, 135, 29])
```

**Вывод:**

```
array([270, 270,  55, 270, -32, 270,  30, 270, 270,  29])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, превышающих или равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[90 116 102 125 108]
 [113 95 130 106 122]
 [110 99 118 104 127]]
Количество элементов массива, превышающих или равных значению середины интервала от a1 до a2: 11
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 30·x² + 27·sin(x) + 26·exp(-x/105)

Запрограммируйте функцию с использованием возможностей numpy

`y = 30*x**2 + 27*sin(x) + 26*exp(-x/105)`

Создайте массив 8×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]
 [1 2 0 3]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]
 [4 3 2 0]
 [1 2 0 3]]
---------------
[[177.74704812 87.38247143 272.06019121 26.        ]
 [482.34144069 177.74704812 87.38247143 272.06019121]
 [26.        272.06019121 177.74704812 482.34144069]
 [87.38247143 26.        482.34144069 177.74704812]
 [272.06019121 482.34144069 26.         87.38247143]
 [177.74704812 26.         87.38247143 272.06019121]
 [482.34144069 272.06019121 177.74704812 26.        ]
 [87.38247143 177.74704812 26.        272.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `c`.

**Ввод**

```
[[26 21 23]
 [20, 24, 22]]

[[17 15 17]
 [15, 16, 15]]

[[14 15 16]
 [15, 14, 15]]
```



**Вывод**

```
[[26 20]
 [21 24]
 [23 22]]

[[43 36 40]
 [35 40 37]]

[[1.85714286 1.4 1.4375]
 [1.33333333 1.71428571 1.46666667]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 9, 4, 7, 2, 8, 3, 5, 1, 0]
b = [4, 8, 3, 6, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
