# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 34

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -33 до -23.

Сделайте это двумя способами:

**Вывод**

```
array([-33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 8×8, где первые семь строк содержат значения `False`, а последняя строка содержит значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 5×5, заполненный случайными целыми числами в интервале от 150 до 200.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении третьей строки третьего столбца
3.   Элемент на пересечении первой строки пятого столбца
4.   Элемент на пересечении пятой строки четвёртого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[199 177 197 184 191]
 [190 195 185 168 187]
 [197 181 197 189 196]
 [194 179 197 186 193]
 [194 179 197 186 193]]
197
191
186
199
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 33.

In [ ]:
test_array = np.array([99, -66, 67, 33, -38, 132, 36, -33, 165, 35])

**Вывод**

```
array([ 99, -66,  33, 132, -33, 165])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 15, и меньше или равны 22.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([14, 30, 41, 22, 22, -27, 38, 22, 35, 21])

**Вывод**

```
array([22, 22, 22, 21])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 33, на `330`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([99, -66, 67, 33, -38, 132, 36, -33, 165, 35])
```

**Вывод:**

```
array([330, 330,  67, 330, -38, 330,  36, 330, 330,  35])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не превышающих значение середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[108 134 120 143 126]
 [131 113 148 124 140]
 [128 117 136 122 145]]
Количество элементов массива, не превышающих значение середины интервала от a1 до a2: 8
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 36·x² + 33·sin(x) + 32·exp(-x/135)

Запрограммируйте функцию с использованием возможностей numpy

`y = 36*x**2 + 33*sin(x) + 32*exp(-x/135)`

Создайте массив 8×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 4 0 1 2]
 [4 3 2 0 1]
 [2 0 4 1 3]
 [1 3 0 2 4]
 [3 0 4 2 1]]
```

**Вывод:**

```
[[2 1 3 0 4]
 [1 2 0 3 4]
 [0 3 2 4 1]
 [3 4 0 1 2]
 [4 3 2 0 1]
 [2 0 4 1 3]
 [1 3 0 2 4]
 [3 0 4 2 1]]
---------------
[[219.74704812 111.38247143 326.06019121 32. 578.34144069]
 [111.38247143 219.74704812 32. 326.06019121 578.34144069]
 [32. 326.06019121 219.74704812 578.34144069 111.38247143]
 [326.06019121 578.34144069 32. 111.38247143 219.74704812]
 [578.34144069 326.06019121 219.74704812 32. 111.38247143]
 [219.74704812 32. 578.34144069 111.38247143 326.06019121]
 [111.38247143 326.06019121 32. 219.74704812 578.34144069]
 [326.06019121 32. 578.34144069 219.74704812 111.38247143]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного возведения в степень** матрицы `a` в степень элементов матрицы `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного остатка от деления** матриц `a` и `c`.

**Ввод**

```
[[32 27 29]
 [26, 30, 28]]

[[23 21 23]
 [21, 22, 21]]

[[20 21 22]
 [21, 20, 21]]
```



**Вывод**

```
[[32 26]
 [27 30]
 [29 28]]

[[1.23794004e+34 1.11403435e+30 1.55121004e+33]
 [9.07751567e+29 1.50094635e+32 1.05101005e+31]]

[[12.  6.  7.]
 [ 5. 10.  7.]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
