# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 6

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -6 до 3.

Сделайте это двумя способами:

**Вывод**

```
array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 7×7 со всеми значениями, равными `True`.

*Подсказка:* создайте массив из единиц и приведите тип массива к `bool`.

**Вывод**

```
array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 3×5, заполненный случайными целыми числами в интервале от 40 до 95.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении первой строки четвёртого столбца
3.   Элемент на пересечении второй строки второго столбца
4.   Элемент на пересечении третьей строки пятого столбца
5.   Последний элемент массива

**Вывод (случайный массив)**

```
[[67 52 84 71 45]
 [58 93 46 79 62]
 [81 54 69 42 88]]
71
93
88
88
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 5.

In [ ]:
test_array = np.array([25, -10, 13, 5, -7, 20, 8, -15, 30, 6])

**Вывод**

```
array([ 25, -10,   5,  20, -15,  30])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 2, и строго меньше 9.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([1, 6, 11, 3, 8, 0, 9, 5, 7, 2])

**Вывод**

```
array([6, 3, 8, 5, 7, 2])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 5, на `25`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([25, -10, 13, 5, -7, 20, 8, -15, 30, 6])
```

**Вывод:**

```
array([25, 25, 13, 25, -7, 25,  8, 25, 25,  6])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[32 58 41 67 49]
 [53 36 72 44 61]
 [47 39 55 42 68]]
Количество элементов массива, не равных значению середины интервала от a1 до a2: 15
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 7·x² + 4·cos(x) + 3·exp(-x/7)

Запрограммируйте функцию с использованием возможностей numpy

`y = 7*x**2 + 4*cos(x) + 3*exp(-x/7)`

Создайте массив 4×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[1 3 2]
 [0 4 1]
 [3 2 0]
 [4 1 3]]
```

**Вывод:**

```
[[1 3 2]
 [0 4 1]
 [3 2 0]
 [4 1 3]]
---------------
[[ 9.38247143 64.06019121 29.87352406]
 [ 3.         114.34144069  9.38247143]
 [64.06019121 29.87352406  3.        ]
 [114.34144069  9.38247143 64.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[3 5 2]
 [4 1 6]]

[[2 3]
 [1 4]
 [3 1]]

[[2 1 3]
 [1 3 2]]
```



**Вывод**

```
[[3 4]
 [5 1]
 [2 6]]

[[17 31]
 [27 22]]

[[ 6  5  6]
 [ 4  3 12]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива строго больше соответствующего элемента второго, и True, если чётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [5, 8, 3, 6, 9, 2, 7, 4, 1, 0]
b = [3, 7, 5, 9, 6, 4, 2, 8, 3, 2]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
