# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 8

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -1 до 7.

Сделайте это двумя способами:

**Вывод**

```
array([-1,  0,  1,  2,  3,  4,  5,  6,  7])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 5×5 со всеми значениями, равными `False`.

*Подсказка:* создайте массив из нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 4×6, заполненный случайными целыми числами в интервале от 20 до 70.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении второй строки пятого столбца
3.   Элемент на пересечении первой строки третьего столбца
4.   Элемент на пересечении четвёртой строки второго столбца
5.   Последний элемент массива

**Вывод (случайный массив)**

```
[[45 62 31 58 47 69]
 [53 38 72 41 56 34]
 [67 29 48 63 52 44]
 [36 51 65 27 59 42]]
56
31
51
42
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 6.

In [ ]:
test_array = np.array([18, -12, 14, 6, -9, 24, 8, -6, 30, 7])

**Вывод**

```
array([ 18, -12,   6,  24,  -6,  30])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 4, и строго меньше 11.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([3, 8, 14, 5, 11, 0, 12, 7, 10, 4])

**Вывод**

```
array([8, 5, 7, 10, 4])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 6, на `60`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([18, -12, 14, 6, -9, 24, 8, -6, 30, 7])
```

**Вывод:**

```
array([60, 60, 14, 60, -9, 60,  8, 60, 60,  7])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, строго меньших или равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[25 52 38 61 44]
 [49 31 67 42 58]
 [46 35 54 40 63]]
Количество элементов массива, строго меньших или равных значению середины интервала от a1 до a2: 7
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 9·x² + 6·cos(x) + 5·exp(-x/10)

Запрограммируйте функцию с использованием возможностей numpy

`y = 9*x**2 + 6*cos(x) + 5*exp(-x/10)`

Создайте массив 3×5 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[1 3 0 2 4]
 [3 1 4 0 2]
 [2 4 1 3 0]]
```

**Вывод:**

```
[[1 3 0 2 4]
 [3 1 4 0 2]
 [2 4 1 3 0]]
---------------
[[13.38247143 82.06019121  5.         38.87352406 147.34144069]
 [82.06019121 13.38247143 147.34144069  5.         38.87352406]
 [38.87352406 147.34144069 13.38247143 82.06019121  5.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[4 2 5]
 [1, 6, 3]]

[[2 4]
 [3, 1]
 [1, 2]]

[[1 2 3]
 [3, 1, 2]]
```



**Вывод**

```
[[4 1]
 [2 6]
 [5 3]]

[[19 28]
 [23 16]]

[[ 4  4 15]
 [ 3  6  6]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если нечётные элементы первого массива больше или равны соответствующему элементу второго, и True, если чётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [3, 8, 5, 6, 9, 2, 7, 4, 1, 0]
b = [2, 7, 6, 9, 5, 4, 3, 8, 5, 3]

```

**Вывод:**

```
[True, False, False, True, True, True, True, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
