# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 23

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -21 до -11.

Сделайте это двумя способами:

**Вывод**

```
array([-21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 4×4, где первые две строки содержат значения `False`, а последние две строки содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 7×7, заполненный случайными целыми числами в интервале от 90 до 140.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении пятой строки седьмого столбца
3.   Элемент на пересечении второй строки пятого столбца
4.   Элемент на пересечении седьмой строки второго столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[119 97 126 103 110 112 121]
 [110 133 115 98 117 119 128]
 [124 106 139 112 101 115 135]
 [108 121 99 130 105 122 131]
 [116 102 128 109 120 104 137]
 [114 107 125 111 134 118 103]
 [122 105 132 113 127 136 129]]
137
117
105
119
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 21.

In [ ]:
test_array = np.array([63, -42, 43, 21, -26, 84, 24, -21, 105, 23])

**Вывод**

```
array([ 63, -42,  21,  84, -21, 105])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 9, и меньше или равны 16.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([8, 18, 29, 15, 16, -15, 26, 16, 23, 14])

**Вывод**

```
array([15, 16, 16, 14])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 21, на `210`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([63, -42, 43, 21, -26, 84, 24, -21, 105, 23])
```

**Вывод:**

```
array([210, 210,  43, 210, -26, 210,  24, 210, 210,  23])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, больших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[72 98 84 107 90]
 [95 77 112 88 104]
 [92 81 100 86 109]]
Количество элементов массива, больших значения середины интервала от a1 до a2: 9
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 24·x² + 21·sin(x) + 20·exp(-x/75)

Запрограммируйте функцию с использованием возможностей numpy

`y = 24*x**2 + 21*sin(x) + 20*exp(-x/75)`

Создайте массив 9×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]
 [4 3 2]
 [1 0 4]
 [3 4 0]]
```

**Вывод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]
 [4 3 2]
 [1 0 4]
 [3 4 0]]
---------------
[[135.74704812 63.38247143 218.06019121]
 [20.        386.34144069 135.74704812]
 [63.38247143 218.06019121 20.        ]
 [386.34144069 135.74704812 63.38247143]
 [218.06019121 20.        386.34144069]
 [135.74704812 63.38247143 20.        ]
 [386.34144069 218.06019121 135.74704812]
 [63.38247143 20.        386.34144069]
 [218.06019121 386.34144069 20.        ]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного остатка от деления** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного вычитания** матриц `a` и `c`.

**Ввод**

```
[[20 15 17]
 [14, 18, 16]]

[[11 9 11]
 [9, 10, 9]]

[[8 9 10]
 [9, 8, 9]]
```



**Вывод**

```
[[20 14]
 [15 18]
 [17 16]]

[[9. 6. 6.]
 [5. 8. 7.]]

[[12  6  7]
 [ 5 10  7]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
