# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 27

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -25 до -15.

Сделайте это двумя способами:

**Вывод**

```
array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 8×8, где первые шесть строк содержат значения `False`, а остальные строки содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 4×4, заполненный случайными целыми числами в интервале от 110 до 160.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении второй строки второго столбца
3.   Элемент на пересечении четвёртой строки третьего столбца
4.   Элемент на пересечении первой строки четвёртого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[147 125 154 131]
 [138 161 143 126]
 [152 134 150 140]
 [145 130 155 148]]
161
155
131
147
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 25.

In [ ]:
test_array = np.array([75, -50, 51, 25, -30, 100, 28, -25, 125, 27])

**Вывод**

```
array([ 75, -50,  25, 100, -25, 125])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 11, и меньше или равны 18.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([10, 22, 33, 18, 18, -19, 30, 18, 27, 17])

**Вывод**

```
array([18, 18, 18, 17])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 25, на `250`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([75, -50, 51, 25, -30, 100, 28, -25, 125, 27])
```

**Вывод:**

```
array([250, 250,  51, 250, -30, 250,  28, 250, 250,  27])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[84 110 96 119 102]
 [107 89 124 100 116]
 [104 93 112 98 121]]
Количество элементов массива, меньших значения середины интервала от a1 до a2: 7
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 28·x² + 25·sin(x) + 24·exp(-x/95)

Запрограммируйте функцию с использованием возможностей numpy

`y = 28*x**2 + 25*sin(x) + 24*exp(-x/95)`

Создайте массив 6×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]]
```

**Вывод:**

```
[[2 1 3 0]
 [4 2 1 3]
 [0 3 2 4]
 [1 0 4 2]
 [3 4 0 1]
 [2 0 1 3]]
---------------
[[163.74704812 79.38247143 254.06019121 24.        ]
 [450.34144069 163.74704812 79.38247143 254.06019121]
 [24.        254.06019121 163.74704812 450.34144069]
 [79.38247143 24.        450.34144069 163.74704812]
 [254.06019121 450.34144069 24.         79.38247143]
 [163.74704812 24.         79.38247143 254.06019121]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного возведения в степень** матрицы `a` в степень элементов матрицы `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `c`.

**Ввод**

```
[[24 19 21]
 [18, 22, 20]]

[[15 13 15]
 [13, 14, 13]]

[[12 13 14]
 [13, 12, 13]]
```



**Вывод**

```
[[24 18]
 [19 22]
 [21 20]]

[[7.07946594e+20 1.51811270e+15 1.59374228e+18]
 [6.13106626e+14 1.29746111e+18 1.30206729e+16]]

[[2.  1.46153846 1.5       ]
 [1.38461538 1.83333333 1.53846154]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 9, 6, 7, 2, 8, 3, 5, 1, 0]
b = [3, 8, 5, 6, 4, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, False]
```

In [ ]:
# ваш код в этой ячейке
