# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 1

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от 1 до 9.

Сделайте это двумя способами:

**Вывод**

```
array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 4×4 со всеми значениями, равными `False`.

*Подсказка:* создайте массив из нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 4×4, заполненный случайными целыми числами в интервале от 10 до 60.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении первой строки второго столбца
3.   Элемент на пересечении второй строки первого столбца
4.   Элемент на пересечении четвёртой строки третьего столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[34 21 55 18]
 [42 13 59 27]
 [38 44 11 52]
 [16 49 33 25]]
21
42
33
34
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите отрицательные элементы этого массива.

In [ ]:
test_array = np.array([3, -5, 0, -2, 8, -9, 1, -4, 6, -1])

**Вывод**

```
array([-5, -2, -9, -4, -1])
```



In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые больше или равны 3, и меньше или равны 7.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([1, 5, 9, 3, 7, 2, 8, 4, 6, 0])

**Вывод**

```
array([5, 3, 7, 4, 6])
```



In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените положительные элементы из массива `test_array` на `-1`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([3, -5, 0, -2, 8, -9, 1, -4, 6, -1])
```

**Вывод:**

```
array([-1, -5,  0, -2, -1, -9, -1, -4, -1, -1])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, меньших или равных значению середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[23 45 12 38 51]
 [34 19 47 28 55]
 [41 33 16 49 22]]
Количество элементов массива, меньших или равных значению середины интервала от a1 до a2: 8
```



In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 3·x² + 4·sin(x) + 2·exp(-x/10)

Запрограммируйте функцию с использованием возможностей numpy

`y = 3*x**2 + 4*sin(x) + 2*exp(-x/10)`

Создайте массив 4×4 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[1 2 3 0]
 [4 1 2 3]
 [0 3 4 1]
 [2 0 1 4]]
```

**Вывод:**

```
[[1 2 3 0]
 [4 1 2 3]
 [0 3 4 1]
 [2 0 1 4]]
---------------
[[ 6.63212056 13.27067057 26.65892427  2.        ]
 [47.81859485  6.63212056 13.27067057 26.65892427]
 [ 2.         26.65892427 47.81859485  6.63212056]
 [13.27067057  2.          6.63212056 47.81859485]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером m×k. Выведите на экран результат умножения матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат умножения элементов матриц `a` и `c`.

**Ввод**

```
[[2 1 4]
 [3 0 2]]

[[1 3]
 [2 0]
 [1 2]]

[[3 2 1]
 [1 4 3]]
```



**Вывод**

```
[[2 3]
 [1 0]
 [4 2]]

[[ 8 14]
 [ 5 13]]

[[ 6  2  4]
 [ 3  0  6]]
```



In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива больше или равны соответствующему элементу второго, и True, если нечётные элементы второго массива строго больше соответствующего элемента первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [4, 6, 3, 8, 1, 7, 2, 5, 9, 0]
b = [3, 5, 4, 7, 2, 8, 1, 6, 4, 2]

```

**Вывод:**

```
[True, True, False, True, False, True, True, False, True, False]
```

In [ ]:
# ваш код в этой ячейке
