# Введение в NumPy. Возможности библиотеки NumPy для работы с массивами. Массивы случайных чисел

# Вариант 21

## Задача 1. Одномерный массив numpy

Создайте одномерный массив чисел от -19 до -9.

Сделайте это двумя способами:

**Вывод**

```
array([-19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9])
```



- с помощью `arange`

In [ ]:
# ваш код тут

- с помощью преобразования списка (list) в numpy `array`

In [ ]:
# ваш код тут

## Задача 2

Создайте массив numpy размером 9×9, где первые шесть строк содержат значения `False`, а остальные строки содержат значения `True`.

*Подсказка:* создайте массив из единиц/нулей и приведите тип массива к `bool`.

**Вывод**

```
array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])
```

In [ ]:
# ваш код тут

## Задача 3

Создайте массив 5×5, заполненный случайными целыми числами в интервале от 80 до 130.
Выведите на экран:

1.   Массив
2.   Элемент на пересечении третьей строки второго столбца
3.   Элемент на пересечении пятой строки пятого столбца
4.   Элемент на пересечении второй строки первого столбца
5.   Первый элемент массива

**Вывод (случайный массив)**

```
[[105 83 112 89 96]
 [96 119 101 84 103]
 [110 92 125 98 87]
 [94 107 85 116 91]
 [102 88 114 95 121]]
92
121
96
105
```



In [ ]:
# ваш код тут

## Задача 4

Вам дан массив под названием `test_array`. Выведите элементы этого массива, кратные 19.

In [ ]:
test_array = np.array([57, -38, 39, 19, -24, 76, 22, -19, 95, 21])

**Вывод**

```
array([ 57, -38,  19,  76, -19,  95])
```

In [ ]:
# ваш код тут

## Задача 5

Вам дан массив `arr`. Выведите все его элементы, которые строго больше 8, и меньше или равны 15.

*Подсказка:* здесь можно использовать булевы маски.

In [ ]:
arr = np.array([7, 16, 27, 13, 15, -13, 24, 15, 21, 14])

**Вывод**

```
array([13, 15, 15, 14])
```

In [ ]:
# ваш код тут

## Задача 6. Замена элементов массива

Замените элементы из массива `test_array`, кратные 19, на `190`.

*Подсказка:* вам пригодится функция `np.where`.

### Пример

**Ввод:**

```
test_array = np.array([57, -38, 39, 19, -24, 76, 22, -19, 95, 21])
```

**Вывод:**

```
array([190, 190,  39, 190, -24, 190,  22, 190, 190,  21])
```

In [ ]:
# ваш код в этой ячейке


## Задача 7. Случайная матрица

Программа принимает на вход четыре числа `n` - количество строк матрицы, `m` - количество столбцов матрицы, `a1` - начало интервала для заполнения матрицы случайными числами, `a2` - конец интервала для заполнения матрицы случайными числами.

Создайте массив `n*m`, заполненный случайными целыми числами в интервале от `a1` до `a2`, и выведите его на экран.
Подсчитайте и выведите на экран количество элементов массива, не меньших значения середины интервала от `a1` до `a2`.

**Вывод (случайный массив)**

```
[[66 92 78 101 84]
 [89 71 106 82 98]
 [86 75 94 80 103]]
Количество элементов массива, не меньших значения середины интервала от a1 до a2: 10
```

In [ ]:
# ваш код тут


## Задача 8. Применим функцию к массиву аргументов

y = 22·x² + 19·sin(x) + 18·exp(-x/65)

Запрограммируйте функцию с использованием возможностей numpy

`y = 22*x**2 + 19*sin(x) + 18*exp(-x/65)`

Создайте массив 7×3 и примените функцию сразу ко всем его аргументам.
На экран вывести исходный массив и результат применения функции.

### Пример

**Ввод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]
 [4 3 2]]
```

**Вывод:**

```
[[2 1 3]
 [0 4 2]
 [1 3 0]
 [4 2 1]
 [3 0 4]
 [2 1 0]
 [4 3 2]]
---------------
[[121.74704812 55.38247143 200.06019121]
 [18.        354.34144069 121.74704812]
 [55.38247143 200.06019121 18.        ]
 [354.34144069 121.74704812 55.38247143]
 [200.06019121 18.        354.34144069]
 [121.74704812 55.38247143 18.        ]
 [354.34144069 200.06019121 121.74704812]]
```

In [ ]:
# ваш код в этой ячейке


## Задача 9. Работа с матрицами

Создайте двумерную матрицу `a` размером n×m.

1. Выведите транспонированную матрицу
2. Создайте матрицу `b`, размером n×m. Выведите на экран результат **поэлементного деления** матриц `a` и `b`.
3. Создайте матрицу `c` размером n×m. Выведите на экран результат **поэлементного сложения** матриц `a` и `c`.

**Ввод**

```
[[18 13 15]
 [12, 16, 14]]

[[9 7 8]
 [7, 8, 7]]

[[6 7 8]
 [7, 6, 7]]
```



**Вывод**

```
[[18 12]
 [13 16]
 [15 14]]

[[2.  1.85714286 1.875]
 [1.71428571 2.  2.   ]]

[[24 20 23]
 [19 22 21]]
```

In [ ]:
# ваш код тут


## Задача 10. Истина или ложь

Дано два одномерных массива. Создайте массив, который получает поэлементно True, если чётные элементы первого массива строго больше соответствующего элемента второго, и True, если нечётные элементы второго массива больше или равны соответствующему элементу первого. В противном случае необходимо возвращать False.

Необходимо реализовать задачу с помощью numpy.

### Пример

**Ввод:**

```
a = [6, 9, 4, 7, 2, 8, 3, 5, 1, 0]
b = [4, 8, 3, 6, 5, 7, 2, 9, 4, 3]

```

**Вывод:**

```
[True, False, True, False, False, True, False, True, False, True]
```

In [ ]:
# ваш код в этой ячейке
